name: CD - Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Change to the project directory
            cd ~/expense_tracker

            # Ensure git repository is clean (optional)
            git reset --hard
            git clean -fd

            # Pull the latest changes from the main branch
            git pull origin main

            # Install dependencies if necessary
            npm install

            # Install pm2 globally if not already installed
            if ! command -v pm2 &> /dev/null
            then
              echo "pm2 not found, installing it..."
              npm install -g pm2
            fi

            # Restart the PM2 process if it's already running, else start a new process
            pm2 restart all || pm2 start server.js --name expense-app
